### ISSUE TITLE
vue2.0- Guide 中文翻译(进度 / 认领)

### ISSUE THREAD

**Issue by dingyiming** [vuefe/vuejs.org#1]
> 网址： http://vuefe.cn
> 加QQ群贡献: `427447379`

### 认领说明

- 翻译前，请在此回复认领
- 认领格式 ：
  - 未完成
     - [ ] 我翻译 + `文档序号 `

- markdown语法 - 示例

```markdown
- [ ] 我翻译 `1`
```

  - 完成后，打钩表示完成，并附带 发起的合并请求链接
     - [x] 我翻译 + `文档序号 ` +  https://github.com/vuefe/vuejs.org/pull/65  (发起的合并请求链接)

- markdown语法 - 示例

```markdown
- [x] 我翻译 + `1 ` https://github.com/vuefe/vuejs.org/pull/65  (发起的合并请求链接)
```

- 支持多人协作翻译，冲突可以解决，认领过的，如果你觉着他太慢，可以再次认领，加速翻译，知道大家都是牺牲业余时间来贡献，所以慢也是可以理解的，慢就需要大家一起帮帮忙了！谢谢。

> 以下所有文档所在目录为 `src/guide/xxx.md`

### Essentials  基础

序号 | 是否完成  | 对应文档文件名 | 中文标题  | 贡献者 | 认领者
----- | ------- | ------------- | --- | --- | ---
1 | 是 |  installation.md | 安装 | @dingyiming | @dingyiming
2 | 是 | index.md |  介绍 | @hijiangtao   | @dingyiming @hijiangtao
3 | 是 | instance.md | 实例 |  @dingyiming | @dingyiming
4 | 是 | syntax.md  | 模板语法 | @daix6  | @tingtien @daix6
5 | 是 | computed.md | 计算属 性 |  @dingyiming | @dingyiming
6 | 是 | class-and-style.md | Class 与 Style 绑定 | @595074187  | @595074187
7 | 是 |  conditional.md  | 条件渲染 | @dingyiming | @dingyiming
8 | 是 | list.md |  列表渲染 | @tingtien | @tingtien
9 | 是 | events.md | 事件处理器 | @dingyiming | @dingyiming
10 | 是 |  forms.md  | 表单控件绑定 | @dingyiming | @dingyiming
11 | 是 | components.md |  组件 | @ezreally  | @ezreally

### Advanced  进阶

序号 | 是否完成  | 对应文档文件名 | 中文标题 | 贡献者 | 认领者
----- | ------- | ------------- | --- | --- | ---
12 | 是 | transitions.md | 过渡: 进入, 离开, 和 列表 | @awe | @awe
13 | 是 | transitioning-state.md | 过渡状态 |  @awe | @awe
14 | 是 | render-function.md |  Render 函数 |  @awe | @awe
15 | 是 | reactivity.md |  深入响应式原理 | @veaba | @veaba
16 | 是 | custom-directive.md |  自定义指令 | @harrytospring | @harrytospring
17 | 是 | mixins.md |  混合 |  @harrytospring | @harrytospring
18 | 是 | plugins.md |  插件 | @hgcoder  | @hgcoder
19 | 是 | single-file-components.md |  单文件组件 | @ATLgo  | @ATLgo 
20 | 是 | routing.md | 路由 | @dingyiming | @dingyiming
21 | 是 | state-management.md |  状态管理 | @dear-lizhihua | @dear-lizhihua
22 | 是 | unit-testing.md | 单元测试 | @70data  | @70data
23 | 是 | ssr.md |  服务端渲染 | @dingyiming | @dingyiming

### Migration  迁移

序号 | 是否完成  | 对应文档文件名 | 中文标题 | 贡献者 | 认领者
----- | ------- | ------------- | --- | --- | ---
24 | 是  | migration.md | 1.x迁移 |  @harrytospring   | @harrytospring 
27 | 是 | migration-vue-router.md | vue-router 0.7.x 迁移 | @forzajuve10  | @forzajuve10 

### Meta  更多

序号 | 是否完成  | 对应文档文件名 | 中文标题 | 贡献者 | 认领者
----- | ------- | ------------- | --- | --- | ---
25 | 是 |  comparison.md |   对比其他框架 |  @yongbolv | @yongbolv @daix6
26 | 是 |  join.md |  加入Vue.js社区 | @daix6   | @daix6

**Comment by harrytospring** [comment]
认领自定义指令及混合试试手，容易的话下面几个都接下来了。。

**Comment by dingyiming** [comment]
@harrytospring 好的，

**Comment by hgcoder** [comment]
认领混合和插件试试水

**Comment by yongbolv** [comment]
我翻译 25

**Comment by ezreally** [comment]
我翻译11

**Comment by tingtien** [comment]
我认领4，等下完成了，再认领其他的

**Comment by dingyiming** [comment]
添加下 关于翻译的基础指引 https://github.com/vuefe/vuejs.org/issues/25
有疑问直接提issue里面

**Comment by dingyiming** [comment]
我重新认领下 #2 ,由于官方更新，需要重新弄下

**Comment by veaba** [comment]
认领下15，本渣贡献下力量。

**Comment by daix6** [comment]
我翻译8

**Comment by dingyiming** [comment]
@tingtien 已合并更新vuefe.cn，请查看是否有问题

**Comment by daix6** [comment]
我翻译25，26

**Comment by 70data** [comment]
我把22剩下没有翻译的翻译了吧。
我是英语渣。

**Comment by dingyiming** [comment]
@70data  翻译什么就具体说编号，我要罗列到表格中去，谢谢

**Comment by 70data** [comment]
@dingyiming 认领下 22 unit-testing

**Comment by hijiangtao** [comment]
@dingyiming 我已经翻译了 index.md （中文对应为介绍页面），是否可以认领该页面？
认领 2？

**Comment by daix6** [comment]
把认领也加到表格中比较易于管理吧？不然其他人也不晓得哪个正在被翻译:joy:

**Comment by dingyiming** [comment]
@daix6 已经更新，刷新即看,同时更新到了vuefe.cn http://vuefe.cn/about/

**Comment by dingyiming** [comment]
@hijiangtao 可以的，你翻译好，推合并吧，支持多人协作翻译，冲突可以解决的

**Comment by dingyiming** [comment]
还有 6 、 19 、21无人领取

**Comment by ATLgo** [comment]
我翻译19

**Comment by dingyiming** [comment]
还有 6 、21无人领取

**Comment by 595074187** [comment]
我翻译6

**Comment by dear-lizhihua** [comment]
我认领21

**Comment by dingyiming** [comment]
@all 感谢大家，

- 目前，guide部分已经全部领取完毕，希望大家加速翻译，目前已经得到vue作者的微博关注，希望我们尽快完成Guide部分的翻译，
- 接下去还有API部分还需要进一步翻译。
- 所有未完成的内容，均支持多人认领，加速翻译，谢谢

**Comment by hijiangtao** [comment]
有个建议：官方英文文档中给出的 markdown 文字链接中有内部链接和外部链接，外部链接可能存在多种协议（http / https），为了保持一致，是不是大家翻译的时候可以都采用 `//` 代替具体协议呢？

例如 `//vuejs.org/` 代替 `https://vuejs.org/`

**Comment by dingyiming** [comment]
@hijiangtao 还是很有道理的，希望大家可以采纳起来吧！

**Comment by dingyiming** [comment]
目前， 还有 `27` 未被领取

**Comment by forzajuve10** [comment]
认领27

**Comment by ATLgo** [comment]
@hijiangtao 我刚刚按你的建议试了一下，但是存在问题，比如
//webpack.github.io/  这个网站不能打开，因为默认这样采用http协议( 我的浏览器是chrome 53)
只能是 https://webpack.github.io/

**Comment by dingyiming** [comment]
@ATLgo 哦哦，那还是保持原貌吧，毕竟 https 或者 http 与对应的网站有关

**Comment by dingyiming** [comment]
如果有遗漏，有需要修正的地方，还请大家优化优化，谢谢。

**Comment by veaba** [comment]
我要尽快完成了，目测今天能完成。

**Comment by hijiangtao** [comment]
@ATLgo @dingyiming 抱歉解释的时候没说清楚，依赖协议是根据 url 所在页面采用的协议进行加载的，目的是为了防止 `This Page Contains Both Secure and Non-Secure Items` 报错。我错误的以为 url 在跳转时是浏览器会自动将其转换。

对于依赖协议，除非使用文件方式打开，`//` 默认采用 http 协议。一般现在用于 https 跨域名地址情况下，即对于 vuejs.org 来说不会存在你说的无法打开的问题（官网两种协议下的请求貌似均可以访问）。vuefe.cn 采用的 http 协议，我刚试了 介绍 页面里使用的这些链接，也是可以正常打开的？ 另外 `webpack.github.io` 使用 http / https 貌似均可以打开（ chrome 53 / firefox 49，我觉得可能是 repo 没有勾选 Enforce HTTPS 的缘故）？

可能我了解的不是特别全面，但是如果持续出现你说的问题，你还是使用全协议拼写为好。:-)

**Comment by daix6** [comment]
我翻译 

-  [x] 4

**Comment by dingyiming** [comment]
感谢大家贡献，终于完成了Guide翻译，接下来还需要进一步校对，希望大家前去
