### ISSUE TITLE
命令行工具中"$ vue init webpack-2.0 my-project"语句已经无效

### ISSUE THREAD

**Issue by MrXin** [vuefe/vuejs.org#108]
新版本默认就是webpack2.0的模板了
应该改成
"$ vue init webpack my-project"

**Comment by dingyiming** [comment]
@MrXin 好的，我来修改下

**Comment by dingyiming** [comment]
@MrXin  好了

![image](https://cloud.githubusercontent.com/assets/12537013/19218083/8ca6607e-8e22-11e6-944b-b63190215780.png)

**Comment by MrXin** [comment]
@dingyiming 棒
