### ISSUE TITLE
"你可以查看 API 文档 的详细说明"。其中api文档链接失效了

### ISSUE THREAD

**Issue by MrXin** [vuefe/vuejs.org#114]
应该把链接地址由
"http://vuefe.cn/router/api/route-object.md"
改成
"http://vuefe.cn/router/api/route-object.html"

**Comment by dingyiming** [comment]
@MrXin  好的，我去改

**Comment by dingyiming** [comment]
@MrXin 改好了http://vuefe.cn/router/essentials/dynamic-matching.html
