### ISSUE TITLE
vuex2 为什么没有开展翻译工作呢

### ISSUE THREAD

**Issue by ShangXinbo** [vuefe/vuejs.org#118]
vue-router2相关文档都已经完成了，但是vuex怎么没有呢，是考虑vue不是必须升级所以才延缓翻译么

**Comment by dingyiming** [comment]
@ShangXinbo 感谢，主要在清理 vue 2 文档 校对工作 - vuex应该会很快开始的。

**Comment by ShangXinbo** [comment]
了解

**Comment by dingyiming** [comment]
@ShangXinbo https://github.com/vuefe/vuejs.org/issues/124 vuex 2.0 翻译认领
