### ISSUE TITLE
vue 2.0 - API 翻译校对 （进度 / 认领）

### ISSUE THREAD

**Issue by dingyiming** [vuefe/vuejs.org#119]
> 建议汇总：https://github.com/vuefe/vuejs.org/issues/48

### 参与：

- 如果你看到错别字、漏译、错译，请直接提交 pr
    （[帮助](https://help.github.com/articles/using-pull-requests/)）。
- 如果你看到网站问题，或者创建一个 issue，或者直接提交 pr。
- 如果你对已有翻译有异议，建议创建一个 issue 讨论。
- 如果你想修改英文内容，请去 [vuejs.org 项目][vuejs.org]。
- 如果你想求教 Vue.js 使用问题，请去[论坛][forum]。
- 如果你遇到 Vue.js 的问题，请去 [vue 项目][vue]，
    创建 issue 并提供演示。可以在 JSBin, JSFiddle, Codepen 等网站创建演示。

### 翻译要求

- 保持一致，清晰
-  汉字，字母，数字等之间以一个空格隔开。
-  中文使用中文符号，英文使用英文符号。
- 专有词注意大小写，如 HTML，CSS，JavaScript。
- 术语与已有译文保持一致，如果有异议请先在 issue 中讨论。
- 代码只翻译注释。
- 标题会转化为链接，文档其它地方可能会用到，所以标题应尽量简短，
    在修改标题时搜索一下它是否还用在其它地方。
    同样的，在修改文档内链接时也应搜索一下。
- 校对后对应修改提交合并请求

### 统一固定词汇翻译

- Type => 类型
- See also => 另见
- Details => 详细
- Options => 选项
- Example => 示例
- Restriction => 限制
- default => 默认值
- prop => 特性（是指 一个 API 时候，不要翻译成中文）
- attribute => 特性
- transition => 过渡

### 术语翻译对照

- attribute 特性
- transition 过渡

### 不翻译的术语

- getter
- setter
- prop（指API时）

## 校对

- 校对 同时校对 格式， 标点符号 格式等，遵循翻译要求

### 认领说明

- 校对前，请在此回复认领
- 认领格式 ：
  - 未完成
     - [ ] 我校对 + `文档序号 `

- markdown语法 - 示例

```markdown
- [ ] 我校对 `1`
```

  - 完成后，打钩表示完成，并附带 发起的合并请求链接
     - [x] 我校对 + `文档序号 ` +  https://github.com/vuefe/vuejs.org/pull/65  (发起的合并请求链接)

- markdown语法 - 示例

```markdown
- [x] 我校对 + `1 ` https://github.com/vuefe/vuejs.org/pull/65  (发起的合并请求链接)
```

- 支持多人协作翻译，冲突可以解决，认领过的，如果你觉着他太慢，可以再次认领，加速翻译，知道大家都是牺牲业余时间来贡献，所以慢也是可以理解的，慢就需要大家一起帮帮忙了！谢谢。

> 文档所为 `src/api/index.md`

## API 校对进度

序号 | 是否完成  | 对应小节名称 | 中文标题  | 翻译贡献者  | 校对贡献者 | 校对认领者
----- | ------- | ------------- | --- | --- | --- | --- | ---
1 | 是 |  Global Config | 全局配置 |  @dear-lizhihua | @bhnddowinf  | @bhnddowinf
2 | 是 | Global API | 全局API | @dear-lizhihua | @bhnddowinf | @bhnddowinf
3 | 是 | Options / Data | 选项 / 数据 | @dear-lizhihua | @bhnddowinf  | @bhnddowinf
4 | 是 | Options / DOM | 选项 / DOM | @ATLgo | @bhnddowinf  | @bhnddowinf
5 | 是 | Options / Lifecycle Hooks | 选项 / 生命周期钩子 | @ATLgo | @bhnddowinf  | @bhnddowinf
6 | 是 | Options / Assets | 选项 / 资源 | @dingyiming | @bhnddowinf  | @bhnddowinf
7 | 是 | Options / Misc | 选项 / 杂项 | @dingyiming  |  @bhnddowinf  | @bhnddowinf
8 | 是 | Instance Properties | 实例属性 | @coolzjy | @bhnddowinf  | @bhnddowinf
9 | 是 | Instance Methods / Data | 实例方法 / 数据 | @dingyiming | @bhnddowinf | @bhnddowinf
10 | 是 | Instance Methods / Events | 实例方法 / 事件 | @mlyknown  | @bhnddowinf | @bhnddowinf
11 | 是 |  Instance Methods / Lifecycle | 实例方法 / 生命周期 | @mlyknown | @bhnddowinf  | @bhnddowinf
12 | 是 | Directives | 指令|   @dingyiming  | @bhnddowinf  | @bhnddowinf
13 | 是 | Special Attributes | 特殊元素 | @70data | @bhnddowinf | @bhnddowinf
14 | 是 | Built-In Components | 内置的组件  | @dear-lizhihua | @bhnddowinf |  @bhnddowinf
15 | 是 | VNode Interface | VNode接口  | @70data | |
16 | 是 | Server-Side Rendering | 服务端渲染| @70data | |

**Comment by bhnddowinf** [comment]
- [ ] 我校对 `1`

**Comment by dingyiming** [comment]
@bhnddowinf 可以多个文档一起提 PR，还是注明，你处理的问题就好了，辛苦了，感谢

**Comment by bhnddowinf** [comment]
针对校对有问题的地方
提出issule吧
毕竟要精准不容易
请直接说那里有问题
修正就好了
避免浪费大家的时间

**Comment by dingyiming** [comment]
## API 校对 ，还有两个未领取
![image](https://cloud.githubusercontent.com/assets/12537013/19299985/1c6c96ec-908a-11e6-9442-465d4cedae9d.png)

**Comment by dear-lizhihua** [comment]
不需要校对，因为只有这两句话，把**请参考**改为**另见：**，调整下格式就OK了。

VNode接口
请参考VNode class declaration.

服务端渲染
请参考vue-server-renderer package documentation.

**Comment by dingyiming** [comment]
@dear-lizhihua 说明还是校对了，哈哈，好的
