### ISSUE TITLE
建议更换代码部分的字体

### ISSUE THREAD

**Issue by banricho** [vuefe/vuejs.org#121]
可以参考官方网站的样式。。。
现在这个字体看代码不太舒服。。。

**Comment by banricho** [comment]
另外：http://vuefe.cn/guide/migration.html

> 通过 data 属性，用prop去设置一个data属性的默认值。//todu

似乎是 `todo` ？

**Comment by banricho** [comment]
> 运行 migration helper 工具找出石勇 debounce 参数的 实例。

使用

**Comment by dingyiming** [comment]
@banricho 你是mac?

**Comment by dingyiming** [comment]
@banricho 两个问题处理掉了

**Comment by dingyiming** [comment]
@banricho 已经更改代码字体为官方字体，看看是不是好一些？

**Comment by banricho** [comment]
@dingyiming 我在 Mac 和 Windows 下都看过最新一般了，似乎还是和官方不一样

官方使用的是 `'Roboto Mono', Monaco, courier, monospace`
此外个人觉得在 Windows 下，大量文字出现时宋体的阅读感优于雅黑

**Comment by dingyiming** [comment]
@banricho 目前代码部分已经恢复官方字体。。。
