### ISSUE TITLE
vuex 2.0 - 文档翻译 （进度 / 认领）

### ISSUE THREAD

**Issue by dingyiming** [vuefe/vuejs.org#124]
> 建议汇总：https://github.com/vuefe/vuejs.org/issues/48
> [翻译规范](https://github.com/vuefe/vuejs.org/wiki/%E7%BF%BB%E8%AF%91%E8%A7%84%E8%8C%83)

- 特别说明：
  - 如果遇到 `xx.md` 形式的链接，请改为 `xx.html` ，即可使链接生效
  -  参考Guide 最后添加原文链接的方法，添加原文链接到每篇文字最后

### 认领说明

- 翻译前，请先阅读翻译规范，后回复认领
- 认领格式 ：
  - 未完成
     - [ ] 我翻译 + `文档序号 `

- markdown语法 - 示例

```markdown
- [ ] 我翻译 `1`
```

  - 完成后，打钩表示完成，并附带 发起的合并请求链接
     - [x] 我翻译+ `文档序号 ` +  https://github.com/vuefe/vuejs.org/pull/65  (发起的合并请求链接)

- markdown语法 - 示例

```markdown
- [x] 我翻译 + `1 ` https://github.com/vuefe/vuejs.org/pull/65  (发起的合并请求链接)
```

- 支持多人协作翻译，冲突可以解决，认领过的，如果你觉着他太慢，可以再次认领，加速翻译，知道大家都是牺牲业余时间来贡献，所以慢也是可以理解的，慢就需要大家一起帮帮忙了！谢谢。

> 以下所有文档所在目录为 `src/vuex/xx.md`

## vuex 2.0 翻译进度

序号 | 是否完成  | 文件名 | 中文标题  |  翻译认领者 | 翻译贡献者 
---- | --- | --- | --- | --- | --- 
1 | 是 | installation.md  | 安装 | @ATLgo | @ATLgo 
2 | 是 | intro.md | 什么是 Vuex ？ | @ATLgo | @ATLgo
3 | 是 | getting-started.md | 起步 |  @ATLgo | @ATLgo
4 | 是 | state.md | State | @dear-lizhihua | @dear-lizhihua 
5 | 是 | getters.md | Getters | @dear-lizhihua | @dear-lizhihua
6 | 是 | mutations.md | Mutations | @dear-lizhihua | @dear-lizhihua
7 | 是 | actions.md | Actions | @dear-lizhihua | @dear-lizhihua
8 | 是 | modules.md | Modules | @yongbolv  | @yongbolv
9 | 是 | structure.md | 应用结构 | @yongbolv  | @yongbolv
10 | 是| plugins.md | 插件 | @yongbolv |@yongbolv
11 | 是 | strict.md | 严格模式 | @yongbolv | @yongbolv
12 | 是 | forms.md | 表单处理 | @veaba | @veaba
13 | 是 | testing.md | 测试 | @veaba | @veaba
14 | 是 | hot-reload.md | 热加载 | @mlyknown | @mlyknow
15 | 是 | api.md| API | @mlyknown  | @mlyknown

**Comment by yongbolv** [comment]
- [ ] 我翻译 `10`
- [ ] 我翻译 `11`

**Comment by veaba** [comment]
- [ ] 我翻译 `2`
- [ ] 我翻译 `12`

**Comment by ATLgo** [comment]
- [ ] 我翻译 `1`
- [ ] 我翻译 `2`
- [ ] 我翻译 `3`

**Comment by dear-lizhihua** [comment]
我翻译5、6、7。
手机打的，明天排版

**Comment by dingyiming** [comment]
@dear-lizhihua 哈哈，感谢，我帮你排好了

**Comment by mlyknown** [comment]
- [ ] 我翻译14
- [ ] 我翻译15

**Comment by dear-lizhihua** [comment]
- [ ] 我翻译 `4`
- [ ] 我翻译 `5`
- [ ] 我翻译 `6`
- [ ] 我翻译 `7`

**Comment by dingyiming** [comment]
@yongbolv @veaba @ATLgo @mlyknown @dear-lizhihua  有个参考文档，可以同时校对下 - http://zhenyong.site/vuex/hot-reload.html

**Comment by yongbolv** [comment]
- [ ] 我翻译 `8`
- [ ] 我翻译 `9`

**Comment by dear-lizhihua** [comment]
https://github.com/vuejs/vuex/blob/1.0/docs/zh-cn/SUMMARY.md
Vuex 1.0中文文档在这里，翻译时可以作为参考。

**Comment by dingyiming** [comment]
![image](https://cloud.githubusercontent.com/assets/12537013/19300008/4426d6de-908a-11e6-8174-506bcd1c9496.png)
![image](https://cloud.githubusercontent.com/assets/12537013/19300014/569aaf3e-908a-11e6-9f07-8d73dba53393.png)
![image](https://cloud.githubusercontent.com/assets/12537013/19300017/5a9b0cd2-908a-11e6-8a55-0f9ff2859f66.png)

**Comment by veaba** [comment]
@dingyiming  已完成。
