### ISSUE TITLE
征求建议 - 为网站添加什么功能，如何提供更好的文档阅读体验？

### ISSUE THREAD

**Issue by dingyiming** [vuefe/vuejs.org#129]
- 目前文档内容，基本完善，保留了 Vue 官方风格以及阅读体验，当然还缺乏一个搜索插件的接入。
- 但我更希望我们能更进一步为文档贡献我们的代码能力。

## 我的一点想法

- 添加搜索插件支持静态站搜索 ，如 vue 官方所用搜索插件
- 添加全文热点功能，类似应用 - 白板 可以点击位置进行交互，或者段落热点交互功能，类似 leancloud文档有的每个段落都可以进行发言交互，

- 你们觉着呢？

**Comment by bhnddowinf** [comment]
步调太快，反而会失去原有的目标，建议：先整合到 vue.js 再说
整合到 vue.js ，尤大怎么整合，我们才会知道接下来的定位在那。

**Comment by dingyiming** [comment]
@bhnddowinf 恩恩，动源码的事情，等后面把文档送到 vue.js 之后，我们自己再看看吧，只是有一点点想法，哈哈

**Comment by ShangXinbo** [comment]
翻译就是翻译，把翻译做好是最好的工作，其他工作缀余

**Comment by dear-lizhihua** [comment]
搜索插件的想法很好。之前找一段文档可能要翻好多处地方。

**Comment by dingyiming** [comment]
官方的搜索插件还是不错的
