### ISSUE TITLE
出错 - 待修复

### ISSUE THREAD

**Issue by dingyiming** [vuefe/vuejs.org#158]
http://vuefe.cn/guide/syntax.html

![5901jqgnudmg 3r0kab5f57](https://cloud.githubusercontent.com/assets/12537013/19263693/1d346a38-8fd0-11e6-9f6e-5874e6689c0c.png)

![g mq dekcev drn7iu 72p](https://cloud.githubusercontent.com/assets/12537013/19263885/100114d2-8fd1-11e6-8a0a-305a3524c2e4.png)

**Comment by 70data** [comment]
已经提了pr
https://github.com/vuefe/vuejs.org/pull/160
