### ISSUE TITLE
guide/comparison.md 小问题

### ISSUE THREAD

**Issue by Remember2015** [vuefe/vuejs.org#159]
line 94, 四句话结尾都是 [ 的 ]
line 109-130, 首行缩进不一致，会导致代码对齐不一致
line 135, [ 的 ] 过多
line 244, 不需要的换行
line 277, 不必要的结尾 [ 的 ]

**Comment by dingyiming** [comment]
@Remember2015 晚点改下，感谢

**Comment by yangzj1992** [comment]
@dingyiming  @Remember2015  已经完成校对了这篇内容，并针对问题进行了修复，可以查看校对后的文章内容，并提些意见。

[#163](https://github.com/vuefe/vuejs.org/pull/163)
[#164](https://github.com/vuefe/vuejs.org/pull/164)
