### ISSUE TITLE
贡献者 - 罗列

### ISSUE THREAD

**Issue by dingyiming** [vuefe/vuejs.org#166]
- 担心可能有人推了修改，但未领取，落下了，在此罗列下，最好自己发个言并附上自己的贡献pr链接，谢谢

**Comment by dear-lizhihua** [comment]
Vue Guide - https://github.com/vuefe/vuejs.org/pull/51/files

**Comment by dingyiming** [comment]
@dear-lizhihua 好像我可以看下github接口有没有办法能直接获取到pr的用户列表

**Comment by dear-lizhihua** [comment]
https://github.com/vuefe/vuejs.org/graphs/contributors?from=2016-08-28&to=2016-10-14&type=c
