### ISSUE TITLE
 项目介绍上网址应当是 HTTP 协议

### ISSUE THREAD

**Issue by viko16** [vuefe/vuejs.org#171]
如图：

![image](https://cloud.githubusercontent.com/assets/5064777/19334014/9ea02664-912b-11e6-88c3-f14dc48d7b66.png)

因为：

> HTTPS is not supported for GitHub Pages using custom domains.

Ref https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by leim** [comment]
其实也可以通过cloudflare来让自定义域名的github pages支持https，只不过仅有用户到cloudflare之间是https的，cloudflare到github之间仍然是http的

**Comment by viko16** [comment]
是的解决方案很多，但在解决之前应当先放正常的链接，避免产生误会 🙈

**Comment by dingyiming** [comment]
@viko16 好，已修改
