### ISSUE TITLE
群号过期了吧，github 上的群号搜索不到。

### ISSUE THREAD

**Issue by SimonTart** [vuefe/vuejs.org#173]
网站上的倒是能搜索到，不过github上项目介绍的群号搜索不到。

**Comment by 70data** [comment]
QQ群 427447379

**Comment by SimonTart** [comment]
@70data  我只是觉得 github 上的群号该更新一下。

**Comment by dingyiming** [comment]
@SimonTart 427447379 恩，丢了个 9 ，已经更新，感谢
