### ISSUE TITLE
Vue.js（读音 /vjuː/, 类似于 view） 是一套构建用户界面的 先进框架。

### ISSUE THREAD

**Issue by ZitQin** [vuefe/vuejs.org#176]
这样翻译比较好：
Vue.js（读音 /vjuː/, 类似于 view）是一个构建数据驱动的 web 界面的库。Vue.js 的目标是通过尽可能简单的 API 实现响应的数据绑定和组合的视图组件。

**Comment by dingyiming** [comment]
@ZitQin 感谢，我考虑下，替换下

**Comment by 70data** [comment]
https://github.com/vuefe/vuejs.org/blob/2.0-cn/src/guide/index.md

**Comment by dingyiming** [comment]
![image](https://cloud.githubusercontent.com/assets/12537013/19348841/815272f4-9182-11e6-848b-bdb4cb05c5d6.png)
好像跟原文不一样额
