### ISSUE TITLE
去掉 vue-resource

### ISSUE THREAD

**Issue by yyx990803** [vuefe/vuejs.org#186]
最近团队讨论了一下，Ajax 本身跟 Vue 并没有什么需要特别整合的地方，使用 fetch polyfill 或是 axios、superagent 等等都可以起到同等的效果，vue-resource 提供的价值和其维护成本相比并不划算，所以决定在不久以后取消对 vue-resource 的官方推荐。已有的用户可以继续使用，但以后不再把 vue-resource 作为官方的 ajax 方案。

这里可以去掉 vue-resource，文档也不必翻译了。

**Comment by galenyuan** [comment]
+1

**Comment by dingyiming** [comment]
@yyx990803 哦，好的

**Comment by leyec** [comment]
刚刚习惯 vue-resource , this.$http 传递的this还是蛮方便的, 最后谢谢上次关于不能过滤空格的答复,最后看文档搞懂了.

**Comment by qianzhangsheng** [comment]
以后项目里可以不引用 vue-resource 了吧？

**Comment by Zenfeder** [comment]
干得漂亮！“请求超时处理”这一功能就让我无法忍受！

**Comment by Zhang-O** [comment]
soga

**Comment by cocosmaker** [comment]
需要jsonp 的怎么办？

**Comment by dingyiming** [comment]
@cocosmaker 并不影响

**Comment by ZaleLoveP** [comment]
我刚刚学习vue，在git上下载了一个项目，可是里面http的jsonp方法都变为未定义了，导致项目运行不了，如何解决呢

**Comment by haoyi2015** [comment]
very good
