### ISSUE TITLE
vue2.0 - Guide新增文档翻译（认领）

### ISSUE THREAD

**Issue by dingyiming** [vuefe/vuejs.org#190]
## 新增文档

序号 | 地址 | 认领者 | 贡献者 
--- | --- | --- | --- 
1 | http://vuefe.cn/guide/deployment.html | @dear-lizhihua | @dear-lizhihua
2 | http://vuefe.cn/guide/migration-vuex.html | @dear-lizhihua |
3 | http://vuefe.cn/guide/migration.html | @fytriht | @fytriht
4 | http://vuefe.cn/guide/migration-vue-router.html | @fytriht |

## 认领方式

- 参考之前认领方式

**Comment by dear-lizhihua** [comment]
- [ ] 我翻译1

**Comment by fytriht** [comment]
- [ ] 我翻译 `3`
- [ ] 我翻译 `4`
