### ISSUE TITLE
鉴于 vuefe.cn 被腾讯提示危险网站问题，寻求解决办法

### ISSUE THREAD

**Issue by dingyiming** [vuefe/vuejs.org#213]
## 目前问题

- 腾讯QQ、QQ浏览器、腾讯管家，会报网站危险，好像就是 `/about` 页面的事情，可能是获取github链接太多

- 微信中已经完成封掉了 `vuefe.cn`

- 是否需要把静态站放到 国内托管？ coding ? 七牛？LeanCloud?

- 出现问题的，请帮忙截图回复，我们一起来看看情况

**Comment by mlyknown** [comment]
是不是和 https 有关系
![qq 20161019114636](https://cloud.githubusercontent.com/assets/12880984/19505026/9ff73438-95f1-11e6-95cc-2d7b9403a0e1.png)

**Comment by dingyiming** [comment]
@mlyknown 我有点打算部署到 `leancloud` 去， https://vuefe.leanapp.cn/

**Comment by cangku** [comment]
coding  page  支持https

**Comment by dingyiming** [comment]
暂且添加https站点 https://vuefe.leanapp.cn
