### ISSUE TITLE
关于翻译版本滞后问题

### ISSUE THREAD

**Issue by Mickey-Wang** [vuefe/vuejs.org#346]
**Guide**的**进阶部分**中，[过渡的-CSS-类名](https://cn.vuejs.org/v2/guide/transitions.html#过渡的-CSS-类名)，[CSS过渡](https://cn.vuejs.org/v2/guide/transitions.html#CSS-过渡)和[CSS动画](https://cn.vuejs.org/v2/guide/transitions.html#CSS-动画)出现严重的翻译版本滞后问题，主要集中在2.1.8版本之后对于v-enter-to和v-leave-to两个类的支持。

**Comment by dingyiming** [comment]
@Mickey-Wang 嗯，疏漏了更新了，没人呢

**Comment by dear-lizhihua** [comment]
@Mickey-Wang 最近我会抽时间更新。

**Comment by dear-lizhihua** [comment]
@Mickey-Wang 过渡章节已更新
