### ISSUE TITLE
ssr没有找到中文文档，想找中文文档或者尝试参与翻译

### ISSUE THREAD

**Issue by a1029563229** [vuefe/vuejs.org#347]
我看所有qq群都满了 所以还是在这里提个issue吧

**Comment by transtone** [comment]
不说人数少吗，qq群都满了。
有空也想做点翻译工作，老大们回复一下？

**Comment by dingyiming** [comment]
@transtone 嗯嗯

**Comment by dear-lizhihua** [comment]
已翻译，https://github.com/dear-lizhihua/vue-ssr-docs
