### ISSUE TITLE
vue2.0- API 中文翻译(进度 / 认领)

### ISSUE THREAD

**Issue by dingyiming** [vuefe/vuejs.org#44]
> 发布地址： http://vuefe.cn
> 官方文档仓库：http://vuejs.org/guide/
> 翻译文档仓库：https://github.com/vuefe/vuejs.org

- 加QQ群参与翻译: `427447379`
- [翻译Guide认领](https://github.com/vuefe/vuejs.org/issues/1)
- [翻译API认领](https://github.com/vuefe/vuejs.org/issues/44)
- [翻译指引](https://github.com/vuefe/vuejs.org/issues/25)

### 说明

- 翻译前，请在此回复认领
- 认领格式 ：
  - 未完成
     - [ ] 我翻译 + `文档序号 `

- markdown语法 - 示例

```markdown
- [ ] 我翻译 `1`
```

  - 完成后，打钩表示完成，并附带 发起的合并请求链接
     - [x] 我翻译 + `文档序号 ` +  https://github.com/vuefe/vuejs.org/pull/65  (发起的合并请求链接)

- markdown语法 - 示例

```markdown
- [x] 我翻译 + `1 ` https://github.com/vuefe/vuejs.org/pull/65  (发起的合并请求链接)
```

- 支持多人协作翻译，冲突可以解决，认领过的，如果你觉着他太慢，可以再次认领，加速翻译，知道大家都是牺牲业余时间来贡献，所以慢也是可以理解的，慢就需要大家一起帮帮忙了！谢谢。

### 关于 API 翻译说明

- 文中多次使用的几个词，请大家保持一致的翻译，参考了 `vue1.x` 翻译
  - `Type`  => 类型
  - `See also` => 另见
  - `Details` => 详细
  - `Options`  => 选项
  - `Example` => 示例
  - `Restriction` => 限制
  - `default` => 默认值
  - `Props` => 特性
  -  `prop` => 特性 （在 `props` 是指 一个 API 时候，不要翻译成中文）
![image](https://cloud.githubusercontent.com/assets/12537013/19184185/85c11e0e-8cae-11e6-9c86-25907a65e8b4.png)

- 冒号 使用中文输入法下的，之前如有问题的，可以修改下。
 
> 以下小节均在 `src/api/index.md` 一个文档中

## API翻译进度

序号 | 是否完成  | 对应小节名称 | 中文标题  | 贡献者 | 认领者
----- | ------- | ------------- | --- | --- | ---
1 | 是 |  Global Config | 全局配置 |  @dear-lizhihua |  @dear-lizhihua
2 | 是 | Global API | 全局API | @dear-lizhihua | @dear-lizhihua
3 | 是 | Options / Data | 选项 / 数据 | @dear-lizhihua | @dear-lizhihua
4 | 是 | Options / DOM | 选项 / DOM | @ATLgo | @ATLgo 
5 | 是 | Options / Lifecycle Hooks | 选项 / 生命周期钩子 | @ATLgo |  @ATLgo 
6 | 是 | Options / Assets | 选项 / 资源 | @dingyiming | @dingyiming
7 | 是 | Options / Misc | 选项 / 杂项 | @dingyiming  |  @dingyiming
8 | 是 | Instance Properties | 实例属性 | @coolzjy | @coolzjy
9 | 是 | Instance Methods / Data | 实例方法 / 数据 | @dingyiming | @dingyiming
10 | 是 | Instance Methods / Events | 实例方法 / 事件 | @mlyknown  | @mlyknown
11 | 是 |  Instance Methods / Lifecycle | 实例方法 / 生命周期 | @mlyknown | @mlyknown
12 | x | Directives | 指令|  |  @tingtien 
13 | 是 | Special Attributes | 特殊元素 | @70data | @70data
14 | 是 | Built-In Components | 内置的组件  | @dear-lizhihua | @dear-lizhihua
15 | 是 | VNode Interface | VNode接口  | @70data | @70data
16 | 是 | Server-Side Rendering | 服务端渲染| @70data | @70data

**Comment by tingtien** [comment]
我翻译API Directives

**Comment by dear-lizhihua** [comment]
我翻译1

**Comment by dear-lizhihua** [comment]
我翻译2、3

**Comment by 70data** [comment]
认领 13 15 16

**Comment by mlyknown** [comment]
认领 10，11

**Comment by ATLgo** [comment]
我翻译4和5

**Comment by dingyiming** [comment]
我翻译 `6`

**Comment by coolzjy** [comment]
+ [ ] 8. Instance Properties 实例属性

**Comment by dear-lizhihua** [comment]
- [ ] 我翻译 `14`

**Comment by dingyiming** [comment]
感谢大家，目前API文档领取完毕，加油！注意版式统一
![image](https://cloud.githubusercontent.com/assets/12537013/19183265/16d771a4-8caa-11e6-8665-740db0a7cb83.png)

**Comment by ATLgo** [comment]
- [x] 我翻译 + `4和5` https://github.com/vuefe/vuejs.org/pull/76

**Comment by dingyiming** [comment]
@tingtien 目前就剩指令未完成了，

**Comment by dingyiming** [comment]
- [x] 我翻译 `12` - 完成
