### ISSUE TITLE
关于翻译 - 建议 与 说明

### ISSUE THREAD

**Issue by dingyiming** [vuefe/vuejs.org#48]
## 在此收集具体 建议与说明

 - 希望大家看清楚需要合并的分支，为`vuefe vuejs.org/2.0-cn` 分支，不要向`vuejs` 官方分支发起合并请求，也不要向 `vuefe vuejs.org/master` 分支发起合并请求，谢谢。

- 两个汉字之间的英文，请加空格，中文文档标点用中文格式，英文文档用英文格式。

**Comment by dingyiming** [comment]
![image](https://cloud.githubusercontent.com/assets/12537013/19139006/aaedd876-8bb3-11e6-83f7-e77d2dec06c9.png)

**Comment by dingyiming** [comment]
- 希望大家看清楚需要合并的分支，为`vuefe vuejs.org/2.0-cn` 分支，不要向`vuejs` 官方分支发起合并请求，也不要向 `vuefe vuejs.org/master` 分支发起合并请求，谢谢。

**Comment by 70data** [comment]
1. 规定一下，两个汉字之间的英文，加不加空格，标点用什么格式等。
2. 列出超链接不能用的地方。
3. 列出翻译有疑义的地方。

**Comment by 70data** [comment]
父/父亲 有多处重复
例如 有的地方翻译为父应用 有的地方翻译为父亲应用 

http://vuefe.cn/guide/installation.html#独立构建-vs-运行时构建
不过得再单文件组件中起作用， 因为单文件组件的模板 是在构建时预编译到 render 函数中
由于一些工具或第三方库引入 Vue , 这可能会导致应用程序运行时加载和独立构建导致错误

http://vuefe.cn/guide/index.html#Vue-js-是什么
Vue 被设计成从底层向上可以被增量式的采用

http://vuefe.cn/guide/instance.html#构造器
我们将在后面详细说明组件系统  超链接失效

http://vuefe.cn/guide/instance.html#属性与方法
不要再实例实现中或者回调函数中（如 vm.$watch('a', newVal => this.myMethod())）使用箭头函数。

http://vuefe.cn/guide/computed.html#计算属性
你不得不停留下意识到显示的是反向的message

http://vuefe.cn/guide/computed.html#Computed-Caching-vs-Methods
还有英文没有翻译

http://vuefe.cn/guide/computed.html#计算属性-vs-watch
考虑下面例子：  是不是翻译成思考较好

http://vuefe.cn/guide/computed.html#观察-Watchers
有时候也很需要一个自定义的数watcher

http://vuefe.cn/guide/computed.html#观察-Watchers
代码内部分英文注释没有翻译

http://vuefe.cn/guide/class-and-style.html#自动添加前缀
当v-bind:style使用需要厂商前缀的 CSS 属性时  翻译成厂商是不是不太便于理解

**Comment by dingyiming** [comment]
@70data 如果是翻译瑕疵，可以直接在源码里面修改，然后提出合并请求，谢谢

**Comment by 70data** [comment]
补充（参照Vue1.0）

翻译基本规范：
汉字，字母，数字等之间以空格隔开。
中文使用中文符号，英文使用英文符号。
专有词注意大小写，如 HTML，CSS，JavaScript。
术语与已有译文保持一致，如果有异议请先在 issue 中讨论。
代码只翻译注释。
统一翻译成父元素、父组件、父作用域。

统一翻译：
Type => 类型
See also => 另见
Details => 详细
Options => 选项
Example => 示例
Restriction => 限制
default => 默认值
prop => 特性（是指 一个 API 时候，不要翻译成中文）
attribute => 特性
transition => 过渡

不翻译的术语：
getter
setter
prop（指API时）

**Comment by einice** [comment]
建议页面html lang设置成zh-CN

**Comment by dingyiming** [comment]
@einice 已经更改

**Comment by whwnow** [comment]
我比较好奇这个翻译会合并到官方么？

**Comment by dingyiming** [comment]
@whwnow 目前我也只能说，有可能。。。

**Comment by whwnow** [comment]
@dingyiming nice!还是并到官方感觉会正式很多

**Comment by Mickey-Wang** [comment]
**Guide**的**进阶部分**中，[过渡的-CSS-类名](https://cn.vuejs.org/v2/guide/transitions.html#过渡的-CSS-类名)，[CSS过渡](https://cn.vuejs.org/v2/guide/transitions.html#CSS-过渡)和[CSS动画](https://cn.vuejs.org/v2/guide/transitions.html#CSS-动画)出现严重的翻译版本滞后问题，主要集中在2.1.8版本之后对于v-enter-to和v-leave-to两个类的支持。
