### ISSUE TITLE
vue2.0 - example 示例内容-  翻译 （进度 / 认领）

### ISSUE THREAD

**Issue by dingyiming** [vuefe/vuejs.org#70]
> 文档地址：http://vuefe.cn/examples/grid-component.html
> 发布地址： http://vuefe.cn
> 官方文档仓库：http://vuejs.org/guide/
> 翻译文档仓库：https://github.com/vuefe/vuejs.org

- 加QQ群参与翻译: `427447379`
- [翻译Guide认领](https://github.com/vuefe/vuejs.org/issues/1)
- [翻译API认领](https://github.com/vuefe/vuejs.org/issues/44)
- [翻译指引](https://github.com/vuefe/vuejs.org/issues/25)

### 说明

- 翻译前，请在此回复认领
- 认领格式 ：
  - 未完成
     - [ ] 我翻译 + `文档序号 `

- markdown语法 - 示例

```markdown
- [ ] 我翻译 `1`
```

  - 完成后，打钩表示完成，并附带 发起的合并请求链接
     - [x] 我翻译 + `文档序号 ` +  https://github.com/vuefe/vuejs.org/pull/65  (发起的合并请求链接)

- markdown语法 - 示例

```markdown
- [x] 我翻译 + `1 ` https://github.com/vuefe/vuejs.org/pull/65  (发起的合并请求链接)
```

- 支持多人协作翻译，冲突可以解决，认领过的，如果你觉着他太慢，可以再次认领，加速翻译，知道大家都是牺牲业余时间来贡献，所以慢也是可以理解的，慢就需要大家一起帮帮忙了！谢谢。

## 认领

直接认领就可以了，内容不多

> 文档在 `src/examples/xx.md` 目录下

![image](https://cloud.githubusercontent.com/assets/12537013/19184636/b0829b16-8cb0-11e6-802a-7fcfaa5cbd8c.png)

## 进度 

- [x] Markdown Editor
- [x] GitHub Commits
- [x] Firebase + Validation
- [x] Grid Component
- [x] Tree View
- [x] SVG Graph
- [x] Modal Component
- [x] Elastic Header
- [x] Wrapper Component
- [x] TodoMVC
- [x] HackerNews Clone

## 后续

- 我们可以自己做点示例放到这个位置来分享，有兴趣的回复下讨论看看。

**Comment by lindazhang102** [comment]
这个翻译我认领
