### ISSUE TITLE
vue 2.0 - Guide 翻译校对 （进度 / 认领）

### ISSUE THREAD

**Issue by dingyiming** [vuefe/vuejs.org#77]
> 建议汇总：https://github.com/vuefe/vuejs.org/issues/48
> [vuejs 1.x 中文翻译规范](https://github.com/vuejs/cn.vuejs.org/blob/lang-zh/CONTRIBUTING.md#%E7%BF%BB%E8%AF%91)
> 请贡献者加群：`543531677`

### 参与：

- 如果你看到错别字、漏译、错译，请直接提交 pr
    （[帮助](https://help.github.com/articles/using-pull-requests/)）。
- 如果你看到网站问题，或者创建一个 issue，或者直接提交 pr。
- 如果你对已有翻译有异议，建议创建一个 issue 讨论。
- 如果你想修改英文内容，请去 [vuejs.org 项目][vuejs.org]。
- 如果你想求教 Vue.js 使用问题，请去[论坛][forum]。
- 如果你遇到 Vue.js 的问题，请去 [vue 项目][vue]，
    创建 issue 并提供演示。可以在 JSBin, JSFiddle, Codepen 等网站创建演示。

### 翻译要求

- 保持一致，清晰
-  汉字，字母，数字等之间以一个空格隔开。
-  中文使用中文符号，英文使用英文符号。
- 专有词注意大小写，如 HTML，CSS，JavaScript。
- 术语与已有译文保持一致，如果有异议请先在 issue 中讨论。
- 代码只翻译注释。
- 标题会转化为链接，文档其它地方可能会用到，所以标题应尽量简短，
    在修改标题时搜索一下它是否还用在其它地方。
    同样的，在修改文档内链接时也应搜索一下。
- 校对后对应修改提交合并请求

### 统一固定词汇翻译

- Type => 类型
- See also => 另见
- Details => 详细
- Options => 选项
- Example => 示例
- Restriction => 限制
- default => 默认值
- prop => 特性（是指 一个 API 时候，不要翻译成中文）
- attribute => 特性
- transition => 过渡

### 术语翻译对照

- attribute 特性
- transition 过渡

### 不翻译的术语

- getter
- setter
- prop（指API时）

### 认领说明

- 校对前，请在此回复认领
- 认领格式 ：
  - 未完成
     - [ ] 我校对 + `文档序号 `

- markdown语法 - 示例

```markdown
- [ ] 我校对 `1`
```

  - 完成后，打钩表示完成，并附带 发起的合并请求链接
     - [x] 我校对 + `文档序号 ` +  https://github.com/vuefe/vuejs.org/pull/65  (发起的合并请求链接)

- markdown语法 - 示例

```markdown
- [x] 我校对 + `1 ` https://github.com/vuefe/vuejs.org/pull/65  (发起的合并请求链接)
```

- 支持多人协作翻译，冲突可以解决，认领过的，如果你觉着他太慢，可以再次认领，加速翻译，知道大家都是牺牲业余时间来贡献，所以慢也是可以理解的，慢就需要大家一起帮帮忙了！谢谢。

> 以下所有文档所在目录为 `src/guide/xxx.md`

### Essentials  基础

序号 | 是否完成  | 对应文档文件名 | 中文标题  | 翻译贡献者 | 校对认领者 |  校对贡献者
----- | ------- | ------------- | --- | --- | --- | --- | ---
1 | 是 |  installation.md | 安装 | @dingyiming  | @ATLgo @70data  | @ATLgo  @70data
2 | 是 | index.md |  介绍 | @hijiangtao  | @ATLgo @70data  | @70data @ATLgo
3 | 是 | instance.md | 实例 |  @dingyiming |  @ATLgo @70data  |  @70data @ATLgo
4 | 是 | syntax.md  | 模板语法 | @daix6  | @70data | @70data
5 | 是 | computed.md | 计算属 性 |  @dingyiming | @70data | @70data
6 | 是 | class-and-style.md | Class 与 Style 绑定 | @595074187 | @70data | @70data
7 | x |  conditional.md  | 条件渲染 | @dingyiming  | @hgcoder  | 
8 | x | list.md |  列表渲染 | @tingtien | @hgcoder  | 
9 | 是 | events.md | 事件处理器 | @dingyiming  | @yangzj1992 | @yangzj1992 
10 | 是 |  forms.md  | 表单控件绑定 | @dingyiming | @yangzj1992 | @yangzj1992 
11 | 是 | components.md |  组件 | @ezreally  | @cuiyongjian  | @cuiyongjian

### Advanced  进阶

序号 | 是否完成  | 对应文档文件名 | 中文标题  | 翻译贡献者 | 校对认领者 |  校对贡献者
----- | ------- | ------------- | --- | --- | --- | ---
12 | 是 | transitions.md | 过渡: 进入, 离开, 和 列表 | @awe  | @bhnddowinf | @bhnddowinf @StoneQI
13 | 是 | transitioning-state.md | 过渡状态 |  @awe  | @bhnddowinf  | @bhnddowinf
14 | 是 | render-function.md |  Render 函数 |  @awe  | @bhnddowinf  | @bhnddowinf 
15 | 是 | reactivity.md |  深入响应式原理 | @veaba | @yangzj1992 | @yangzj1992
16 | 是 | custom-directive.md |  自定义指令 | @harrytospring | @yangzj1992 | @yangzj1992
17 | 是 | mixins.md |  混合 |  @harrytospring | @bhnddowinf  | @bhnddowinf 
18 | x | plugins.md |  插件 | @hgcoder   | @hgcoder  | 
19 | 是 | single-file-components.md |  单文件组件 | @ATLgo  | @zhouzihanntu | @zhouzihanntu
20 | x | routing.md | 路由 | @dingyiming  | @mlyknown | 
21 | 是 | state-management.md |  状态管理 | @dear-lizhihua | @mlyknown |  @mlyknown
22 | 是 | unit-testing.md | 单元测试 | @70data  | @mlyknown |  @mlyknown 
23 | 是 | ssr.md |  服务端渲染 | @dingyiming | @yongbolv | @yongbolv

### Migration  迁移

序号 | 是否完成  | 对应文档文件名 | 中文标题 | 翻译贡献者 | 校对认领者 |  校对贡献者
----- | ------- | ------------- | --- | --- | --- | ---
24 | x  | migration.md | 1.x迁移 |  @harrytospring   | @yongbolv |
27 | x | migration-vue-router.md | vue-router 0.7.x 迁移 | @forzajuve10   | @yizhixiaolongxia  |

### Meta  更多

序号 | 是否完成  | 对应文档文件名 | 中文标题 |  翻译贡献者 | 校对认领者 |  校对贡献者
----- | ------- | ------------- | --- | --- | --- | ---
25 | 是 |  comparison.md |   对比其他框架 |  @yongbolv  | @yangzj1992 | @yangzj1992
26 | 是 |  join.md |  加入Vue.js社区 | @daix6   | @zhouzihanntu | @zhouzihanntu

**Comment by ATLgo** [comment]
- [ ] 我校对 `1`
- [ ] 我校对 `2`
- [ ] 我校对 `3`

**Comment by 70data** [comment]
@ATLgo  1 installation.md 格式与翻译不通顺的地方 已完成校对
@dingyiming  合并时请注意冲突

**Comment by 70data** [comment]
2 index.md 格式与翻译不通顺的地方 已完成校对

**Comment by 70data** [comment]
3 instance.md 格式与翻译不通顺的地方 已完成校对

**Comment by 70data** [comment]
- [ ]  基础校对 1 
- [ ]  基础校对 2
- [ ]  基础校对 3

**Comment by hgcoder** [comment]
我想对 6 7 8

**Comment by veaba** [comment]
本渣就参与校对了，翻译有误的话，轻喷哈

**Comment by hgcoder** [comment]
我校队 7 8 9  18

**Comment by hgcoder** [comment]
我校对 7 8 18

**Comment by yongbolv** [comment]
- [ ] 我校对 `23`
- [ ] 我校对 `24`

**Comment by 70data** [comment]
- [ ]  校对 4
- [ ]  校对 5
- [ ]  校对 6

**Comment by yangzj1992** [comment]
- [ ] 我校对 `9`
- [ ] 我校对 `10`

**Comment by cuiyongjian** [comment]
- [ ] 我校对 `11`

**Comment by bhnddowinf** [comment]
- [ ] 我校对12

**Comment by mlyknown** [comment]
我校对20 
我校对21 
我校对22

**Comment by bhnddowinf** [comment]
- [ ] 我校对13

**Comment by bhnddowinf** [comment]
- [ ] 我校对14

**Comment by yangzj1992** [comment]
@dingyiming  补充申请
- [ ]  我校对 `15` 
- [ ]  我校对 `16`

**Comment by yongbolv** [comment]
[x] 我校对 + `23 ` https://github.com/vuefe/vuejs.org/pull/113

**Comment by yongbolv** [comment]
- [x] 我校对 `23` https://github.com/vuefe/vuejs.org/pull/113

**Comment by zhouzihanntu** [comment]
- [ ] 我校对 `19`
- [ ] 我校对 `26`

**Comment by bhnddowinf** [comment]
- [ ]  我校对 17

**Comment by yizhixiaolongxia** [comment]
我校对27

**Comment by dingyiming** [comment]
## 目前翻译校对未完成情况
![image](https://cloud.githubusercontent.com/assets/12537013/19299836/52ee8ec4-9089-11e6-8d7c-a687967ba1db.png)
![image](https://cloud.githubusercontent.com/assets/12537013/19299841/576fd3a4-9089-11e6-8417-db1a58f7124a.png)
![image](https://cloud.githubusercontent.com/assets/12537013/19299878/87e67740-9089-11e6-9a3e-63940562a833.png)
![image](https://cloud.githubusercontent.com/assets/12537013/19299880/8d8851d2-9089-11e6-973e-95909693a9ca.png)

**Comment by StoneQI** [comment]
- [ ] 我校对 `12`

**Comment by StoneQI** [comment]
- [x] 我校对 + `12` https://github.com/vuefe/vuejs.org/pull/180

**Comment by Creabine** [comment]
- [ ] 我校对 `7`

**Comment by Creabine** [comment]
- [x] 我校对 + `1 ` https://github.com/vuefe/vuefe.github.io/pull/236

**Comment by Creabine** [comment]
- [x] 我校对 + `1 ` https://github.com/vuefe/vuefe.github.io/pull/236

**Comment by Creabine** [comment]
- [x] 我校对 + `1 ` https://github.com/vuefe/vuefe.github.io/pull/236

**Comment by Creabine** [comment]
- [x] 我校对 + `1 ` https://github.com/vuefe/vuefe.github.io/pull/236

**Comment by Creabine** [comment]
- [x] 我校对 + `1 ` https://github.com/vuefe/vuefe.github.io/pull/236

**Comment by Creabine** [comment]
- [x] 我校对 + `1 ` https://github.com/vuefe/vuefe.github.io/pull/236

**Comment by Creabine** [comment]
- [x] 我校对 + `1 ` https://github.com/vuefe/vuefe.github.io/pull/236
