### ISSUE TITLE
代码字体需要和官方的一致吗？

### ISSUE THREAD

**Issue by SidKwok** [vuefe/vuejs.org#97]
看了一下官方使用的是`'Roboto Mono', Monaco, courier, monospace;`，感觉这个代码字体更自然一点。

**Comment by dingyiming** [comment]
我来换换看，就怕系统没这个字体，因为官方是自己下字体包的，怕影响速度，就换了比较中庸的，系统能有的字体

**Comment by SidKwok** [comment]
嗯，还是留给官方决定吧
